import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { collectRelativeFilePaths } from "../../core/file-paths";
import {
	matchesTemplateForbiddenPattern,
	TEMPLATE_FORBIDDEN_PATTERNS,
} from "../../schemas/template-policy";

export type TemplateFileEntry = {
	path: string;
	contentBase64: string;
	sha256: string;
	bytes: number;
};

export type TemplateFileMap = Record<string, TemplateFileEntry>;

export type TemplatePayload = {
	sourceRoot: string;
	sourceFileCount: number;
	includedFileCount: number;
	excludedForbiddenCount: number;
	generatedAt: string;
	templateHash: string;
	files: TemplateFileMap;
};

function sha256Hex(value: string | Uint8Array): string {
	return createHash("sha256").update(value).digest("hex");
}

function canonicalTemplateContent(content: Buffer): Buffer {
	return Buffer.from(content.toString("utf8").replaceAll("\r\n", "\n"), "utf8");
}

function reproducibleGeneratedAt(): string {
	const sourceDateEpoch = process.env.SOURCE_DATE_EPOCH;
	if (sourceDateEpoch && /^[0-9]+$/.test(sourceDateEpoch)) {
		return new Date(Number(sourceDateEpoch) * 1000).toISOString();
	}
	return "1970-01-01T00:00:00.000Z";
}

export async function buildTemplatePayload(
	sourceRoot: string,
): Promise<TemplatePayload> {
	const relativeFilePaths = await collectRelativeFilePaths(sourceRoot);
	const files: TemplateFileMap = {};
	let excludedForbiddenCount = 0;
	let includedFileCount = 0;

	for (const relativePath of relativeFilePaths) {
		if (matchesTemplateForbiddenPattern(relativePath)) {
			excludedForbiddenCount += 1;
			continue;
		}

		const absolutePath = join(sourceRoot, relativePath);
		const content = canonicalTemplateContent(await readFile(absolutePath));
		const contentBase64 = content.toString("base64");
		const sha256 = sha256Hex(content);

		files[relativePath] = {
			path: relativePath,
			contentBase64,
			sha256,
			bytes: content.byteLength,
		};
		includedFileCount += 1;
	}

	const templateHashSeed = Object.entries(files)
		.sort(([left], [right]) => left.localeCompare(right))
		.map(([path, entry]) => `${path}:${entry.sha256}`)
		.join("\n");

	return {
		sourceRoot,
		sourceFileCount: relativeFilePaths.length,
		includedFileCount,
		excludedForbiddenCount,
		generatedAt: reproducibleGeneratedAt(),
		templateHash: sha256Hex(templateHashSeed),
		files,
	};
}

export function renderTemplateModule(payload: TemplatePayload): string {
	const files = JSON.stringify(payload.files, null, 2);
	const metadata = JSON.stringify(
		{
			sourceRoot: payload.sourceRoot,
			sourceFileCount: payload.sourceFileCount,
			includedFileCount: payload.includedFileCount,
			excludedForbiddenCount: payload.excludedForbiddenCount,
			generatedAt: payload.generatedAt,
			templateHash: payload.templateHash,
			forbiddenPatterns: [...TEMPLATE_FORBIDDEN_PATTERNS],
		},
		null,
		2,
	);

	return [
		"/* eslint-disable */",
		"// Auto-generated by cli/dev/generate-template.ts. Do not edit manually.",
		"",
		"export type GeneratedTemplateFile = {",
		"  path: string;",
		"  contentBase64: string;",
		"  sha256: string;",
		"  bytes: number;",
		"};",
		"",
		"export const DEFAULT_TEMPLATE_METADATA = Object.freeze(",
		`${metadata}`,
		");",
		"",
		"export const DEFAULT_TEMPLATE_FILES: Readonly<Record<string, GeneratedTemplateFile>> = Object.freeze(",
		`${files}`,
		");",
		"",
		"export const DEFAULT_TEMPLATE_HASH = DEFAULT_TEMPLATE_METADATA.templateHash;",
		"",
	].join("\n");
}

export function renderBuiltinAssetsModule(payload: TemplatePayload): string {
	const files = JSON.stringify(payload.files, null, 2);
	const metadata = JSON.stringify(
		{
			sourceRoot: payload.sourceRoot,
			sourceFileCount: payload.sourceFileCount,
			includedFileCount: payload.includedFileCount,
			generatedAt: payload.generatedAt,
			assetsHash: payload.templateHash,
		},
		null,
		2,
	);

	return [
		"/* eslint-disable */",
		"// Auto-generated by cli/dev/generate-template.ts. Do not edit manually.",
		"",
		"export type GeneratedBuiltinAsset = {",
		"  path: string;",
		"  contentBase64: string;",
		"  sha256: string;",
		"  bytes: number;",
		"};",
		"",
		"export const BUILTIN_ASSET_METADATA = Object.freeze(",
		`${metadata}`,
		");",
		"",
		"export const BUILTIN_ASSET_FILES: Readonly<Record<string, GeneratedBuiltinAsset>> = Object.freeze(",
		`${files}`,
		");",
		"",
		"export const BUILTIN_ASSET_HASH = BUILTIN_ASSET_METADATA.assetsHash;",
		"",
	].join("\n");
}
