#!/usr/bin/env python3
"""
Agents Index - Update INDEX.md files for SPECS and ADRs.

Scans:
- docs/arc/SPECS/ for spec files
- docs/arc/DECISIONS/ for adr files

Updates:
- docs/arc/SPECS/INDEX.md
- docs/arc/DECISIONS/INDEX.md

Usage:
    python agents-index.py [--dry-run]
"""

import sys
from pathlib import Path
from datetime import datetime
from typing import List

try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False

from lib.agents_config import get_cfg_path, load_agents_config, parse_offset
from lib.markdown_docs import split_markdown_frontmatter as split_frontmatter

# Configuration
ROOT_DIR, CONFIG = load_agents_config(Path(__file__).resolve().parent)
AGENTS_DIR = get_cfg_path(ROOT_DIR, CONFIG, "agents_dir")
SPECS_DIR = get_cfg_path(ROOT_DIR, CONFIG, "specs_dir")
DECISIONS_DIR = get_cfg_path(ROOT_DIR, CONFIG, "decisions_dir")
DEFAULT_OFFSET = CONFIG.get("time", {}).get("default_offset", "+00:00")
DEFAULT_TZ = parse_offset(DEFAULT_OFFSET)


class DocEntry:
    def __init__(self, file_path: Path, doc_type: str):
        self.file_path = file_path
        self.doc_type = doc_type
        self.id = ""
        self.theme = ""
        self.status = ""
        self.owner = ""
        self.created_at = ""
        self.links = []

        self._parse_frontmatter()

    def _parse_frontmatter(self):
        """Parse YAML frontmatter."""
        content = self.file_path.read_text()

        if not content.startswith("---"):
            return

        parts = content.split("---", 2)
        if len(parts) < 3:
            return

        frontmatter_text = parts[1].strip()

        if HAS_YAML:
            try:
                fm = yaml.safe_load(frontmatter_text)
                self.id = fm.get("id", "")
                self.theme = fm.get("theme", fm.get("topic", ""))
                self.status = fm.get("status", "")
                owners = fm.get("owners", [])
                self.owner = owners[0] if owners else ""
                self.created_at = fm.get("created_at", fm.get("created", ""))
                self.links = fm.get("links", {})
            except yaml.YAMLError:
                pass
        else:
            # Basic parsing without yaml
            for line in frontmatter_text.splitlines():
                if line.startswith("id:"):
                    self.id = line.split(":", 1)[1].strip().strip('"')
                elif line.startswith("theme:") or line.startswith("topic:"):
                    self.theme = line.split(":", 1)[1].strip().strip('"')
                elif line.startswith("status:"):
                    self.status = line.split(":", 1)[1].strip().strip('"')

    def to_markdown_row(self) -> str:
        """Convert to markdown table row."""
        links_str = ""
        if self.links:
            link_parts = []
            if isinstance(self.links, dict):
                for key, value in self.links.items():
                    if value:
                        link_parts.append(f"{key}: {value}")
            links_str = ", ".join(link_parts)

        return f"| {self.id} | {self.theme} | {self.status} | {self.owner} | {links_str} |"


def scan_docs(directory: Path, pattern: str, recursive: bool = False) -> List[DocEntry]:
    """Scan directory for doc files."""
    if not directory.exists():
        return []

    entries = []
    files = directory.rglob(pattern) if recursive else directory.glob(pattern)

    for file_path in files:
        if file_path.name.startswith("TEMPLATE_") or file_path.name == "INDEX.md" or file_path.name == "README.md":
            continue

        # Determine doc type from filename
        if "spec" in file_path.name.lower():
            doc_type = "spec"
        elif "adr" in file_path.name.lower():
            doc_type = "adr"
        else:
            doc_type = "unknown"

        entry = DocEntry(file_path, doc_type)
        entries.append(entry)

    # Sort by created_at
    entries.sort(key=lambda e: e.created_at or "")

    return entries


def generate_index(
    entries: List[DocEntry],
    doc_type: str,
    created_at: str | None = None,
    updated_at: str | None = None,
) -> str:
    """Generate INDEX.md content."""
    now_ts = datetime.now(DEFAULT_TZ).strftime(f"%Y-%m-%dT%H:%M:%S{DEFAULT_OFFSET}")
    created_at = created_at or now_ts
    updated_at = updated_at or now_ts
    frontmatter_doc_type = "specs_index" if doc_type == "spec" else "adr_index"
    index_id = "specs_index" if doc_type == "spec" else "adr_index"
    title = "SPECS" if doc_type == "spec" else "ADRS"
    target_dir = SPECS_DIR if doc_type == "spec" else DECISIONS_DIR
    path_label = str((target_dir / "INDEX.md").resolve().relative_to(ROOT_DIR.resolve()))

    content = f"""---
doc_type: {frontmatter_doc_type}
id: "{index_id}"
status: active
created_at: "{created_at}"
updated_at: "{updated_at}"
---

# {title} INDEX

*Auto-generated by `agents-index.py`*

## Summary

<!-- markdownlint-disable MD013 MD060 -->

| Metric | Count |
|--------|-------|
| Total | {len(entries)} |
| Draft | {len([e for e in entries if e.status == 'draft'])} |
| Active | {len([e for e in entries if e.status == 'active'])} |
| Final | {len([e for e in entries if e.status == 'final'])} |

## Index

| {doc_type.upper()} ID | Theme | Status | Owner | Links |
|--------:|-------|--------|-------|------|
"""

    if entries:
        for entry in entries:
            content += entry.to_markdown_row() + "\n"
    else:
        content += "| - | - | - | - | - |\n"

    content += f"""
<!-- markdownlint-enable MD013 MD060 -->

---
*Index: `{path_label}`*
"""

    return content


def extract_existing_timestamps(path: Path) -> tuple[str | None, str | None]:
    if not path.exists():
        return None, None
    parsed = split_frontmatter(path.read_text())
    if not parsed:
        return None, None
    frontmatter, _ = parsed
    created_at = frontmatter.get("created_at")
    updated_at = frontmatter.get("updated_at")
    return (
        str(created_at).strip() if created_at else None,
        str(updated_at).strip() if updated_at else None,
    )


def write_index_if_changed(index_path: Path, entries: List[DocEntry], doc_type: str, dry_run: bool) -> str:
    now_ts = datetime.now(DEFAULT_TZ).strftime(f"%Y-%m-%dT%H:%M:%S{DEFAULT_OFFSET}")
    previous = index_path.read_text() if index_path.exists() else ""
    created_at, updated_at = extract_existing_timestamps(index_path)
    created_at = created_at or now_ts
    stable_updated_at = updated_at or now_ts

    stable_content = generate_index(entries, doc_type, created_at, stable_updated_at)
    if previous == stable_content:
        return "unchanged"

    next_content = generate_index(entries, doc_type, created_at, now_ts)
    if previous == next_content:
        return "unchanged"

    if dry_run:
        return "would_update"

    index_path.write_text(next_content)
    return "updated"


def main():
    dry_run = "--dry-run" in sys.argv

    print("=" * 60)
    print("AGENTS INDEX - Update INDEX.md files")
    print("=" * 60)
    print()

    # Scan SPECS
    print("Scanning SPECS...")
    spec_entries = scan_docs(SPECS_DIR, "*.md", recursive=True)
    print(f"  Found {len(spec_entries)} spec file(s)")

    # Scan DECISIONS
    print("Scanning DECISIONS...")
    adr_entries = scan_docs(DECISIONS_DIR, "*.md")
    print(f"  Found {len(adr_entries)} ADR file(s)")

    print()

    # Generate SPECS index
    if spec_entries:
        specs_index_path = SPECS_DIR / "INDEX.md"
        status = write_index_if_changed(specs_index_path, spec_entries, "spec", dry_run)
        if status == "would_update":
            print(f"[DRY RUN] Would update: {specs_index_path}")
        elif status == "updated":
            print(f"✓ Updated: {specs_index_path}")
        else:
            print(f"= Unchanged: {specs_index_path}")
    else:
        print("⚠️  No spec files found, skipping SPECS index")

    # Generate ADRs index
    if adr_entries:
        adrs_index_path = DECISIONS_DIR / "INDEX.md"
        status = write_index_if_changed(adrs_index_path, adr_entries, "adr", dry_run)
        if status == "would_update":
            print(f"[DRY RUN] Would update: {adrs_index_path}")
        elif status == "updated":
            print(f"✓ Updated: {adrs_index_path}")
        else:
            print(f"= Unchanged: {adrs_index_path}")
    else:
        print("⚠️  No ADR files found, skipping ADRS index")

    print()
    print("=" * 60)

    if dry_run:
        print("DRY RUN - No files were modified")
        print("Run without --dry-run to update indexes")

    print("=" * 60)


if __name__ == "__main__":
    main()
