import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

type PackageMetadata = {
	name: string;
	version: string;
};

const SEMVER_PATTERN =
	/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/;

function assertValidVersion(value: string, label: string): void {
	if (!SEMVER_PATTERN.test(value)) {
		throw new Error(`${label} must be a valid semver string`);
	}
	if (value === "0.0.0") {
		throw new Error(`${label} must not use placeholder 0.0.0`);
	}
}

function readPackageMetadata(): PackageMetadata {
	const raw = JSON.parse(
		readFileSync("package.json", "utf8"),
	) as Partial<PackageMetadata>;
	if (typeof raw.name !== "string" || raw.name.length === 0) {
		throw new Error("package.json name must be a non-empty string");
	}
	if (typeof raw.version !== "string" || raw.version.length === 0) {
		throw new Error("package.json version must be a non-empty string");
	}
	assertValidVersion(raw.version, "package.json version");
	return { name: raw.name, version: raw.version };
}

function renderVersionModule(metadata: PackageMetadata): string {
	return [
		"// Auto-generated by cli/dev/generate-version.ts. Do not edit manually.",
		`export const CLI_PACKAGE_NAME = ${JSON.stringify(metadata.name)};`,
		`export const CLI_VERSION = ${JSON.stringify(metadata.version)};`,
		"",
	].join("\n");
}

const outputPath = "cli/generated/version.ts";
const metadata = readPackageMetadata();
const expected = renderVersionModule(metadata);

if (process.argv.includes("--check")) {
	const actual = readFileSync(outputPath, "utf8");
	if (actual !== expected) {
		console.error(`${outputPath} is stale. Run: bun run version:generate`);
		process.exit(1);
	}
	console.log("version metadata: ok");
	process.exit(0);
}

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, expected, "utf8");
console.log(`version metadata: wrote ${outputPath}`);
