import { readFileSync, writeFileSync } from "node:fs";

type PackageMetadata = {
  name: string;
  version: string;
};

function readPackageMetadata(): PackageMetadata {
  const raw = JSON.parse(readFileSync("package.json", "utf8")) as Partial<PackageMetadata>;
  if (typeof raw.name !== "string" || raw.name.length === 0) {
    throw new Error("package.json name must be a non-empty string");
  }
  if (typeof raw.version !== "string" || raw.version.length === 0) {
    throw new Error("package.json version must be a non-empty string");
  }
  return { name: raw.name, version: raw.version };
}

function renderVersionModule(metadata: PackageMetadata): string {
  return [
    "// Auto-generated by cli/dev/generate-version.ts. Do not edit manually.",
    `export const CLI_PACKAGE_NAME = ${JSON.stringify(metadata.name)};`,
    `export const CLI_VERSION = ${JSON.stringify(metadata.version)};`,
    "",
  ].join("\n");
}

const outputPath = "cli/generated/version.ts";
const expected = renderVersionModule(readPackageMetadata());

if (process.argv.includes("--check")) {
  const actual = readFileSync(outputPath, "utf8");
  if (actual !== expected) {
    console.error(`${outputPath} is stale. Run: bun run version:generate`);
    process.exit(1);
  }
  console.log("version metadata: ok");
  process.exit(0);
}

writeFileSync(outputPath, expected, "utf8");
console.log(`version metadata: wrote ${outputPath}`);
